export type Project = { slug:string; title:string; year:string; engine:string; duration:string; team:string; hero:string; images:string[]; summary:string; brief:string; role:string; tags:string[]; links:{label:string;href:string}[]; systems:{title:string;description:string;details:string[]}[]; outcome:string; learning:string };

export const projects:Project[] = [
  { slug:"virtual-life-support", title:"Virtual Life Support", year:"2026", engine:"Unity VR · Meta Quest", duration:"8 weeks", team:"5 people", hero:"/images/virtual-life-support/hero.jpg", images:["/images/virtual-life-support/hero.jpg","/images/virtual-life-support/01.png"], summary:"A hand-tracked CPR training prototype built for a real client, with physical chest compression, live performance feedback, and a complete scenario flow.", brief:"Virtual Life Support asked us to explore a new CPR scenario for its training platform. We researched how people learn CPR, spoke with people who had taught or performed it, and built a stressful playground scenario where the user has to follow the right procedure while distractions keep happening around them.", role:"I focused on programming the CPR interaction, the live feedback monitor, and the flag system that controls scenario progression. I also helped shape the environment, player guidance, and team planning. I was a major programming contributor, but this was a five-person project and the final prototype was a team result.", tags:["Unity","C#","VR","Hand tracking","Interaction design"], links:[{label:"LinkedIn project post",href:"https://www.linkedin.com/feed/update/urn:li:activity:7419451513338548224/"}], systems:[
    {title:"Hand-tracked CPR",description:"The player has to place both hands correctly before the chest can be compressed. A spring-and-damper model turns hand movement into continuous compression rather than a simple button press.",details:["Dual-hand and chest-zone validation","Compression depth linked to the hand pose","Warm-up period before BPM is calculated"]},
    {title:"Feedback that stays inside the scene",description:"An in-world monitor displays compression rhythm, depth, and quality. Compression events also drive an ECG-style line so the player sees an immediate response without leaving the scenario.",details:["Event-driven waveform","World-space BPM and depth readouts","Colour feedback for correct and incorrect ranges"]},
    {title:"Scenario progression",description:"A shared flag system keeps the scenario in the correct order without hard-wiring every interaction to the next one. The same setup controls NPC requests, distractions, CPR, and AED steps.",details:["Reusable conditions","Actions unlock only when prerequisites are complete","Systems react to events instead of directly depending on each other"]}], outcome:"The prototype received 11/12 points and was selected as the strongest of five student prototypes. The client was particularly positive about how much of the scenario worked within the eight-week block.", learning:"This was my first project with a real external client. I learned that believable VR interaction depends as much on input validation and clear feedback as it does on physics. I also had to clean up early scripts into reusable systems because the scenario kept growing." },
  { slug:"tiny-spider-tiny-home", title:"Tiny Spider Tiny Home", year:"2025", engine:"Unity", duration:"15 weeks", team:"5 people", hero:"/images/tiny-spider/hero.jpg", images:["/images/tiny-spider/hero.jpg","/images/tiny-spider/01.png","/images/tiny-spider/02.png","/images/tiny-spider/03.png","/images/tiny-spider/04.png","/images/tiny-spider/05.png","/images/tiny-spider/06.png","/images/tiny-spider/07.png","/images/tiny-spider/08.png"], summary:"A small spider crosses walls, furniture, and ceilings to switch off appliances before its owner’s energy bill gets out of hand.", brief:"The project had to make household energy use understandable without turning into a lecture. We made the player a spider whose home depends on a student keeping the apartment. Saving energy became the reason to explore the room rather than a message placed on top of the game.", role:"I programmed the spider movement, web-swinging, camera, and interaction system in C#. I also helped arrange the room around those mechanics and built the opening prompts and settings UI.", tags:["Unity","C#","Movement","Camera","Interaction systems"], links:[{label:"GitHub",href:"https://github.com/DylanoSpks/Tiny-Spider-Tiny-Home"},{label:"Download build",href:"https://www.dropbox.com/scl/fi/wrz5v9rhpgfmupac32r56/TinySpiderTinyHome.exe?rlkey=kox9tyhxfy50000pahcybk43i&st=15tt0pub&dl=0"}], systems:[
    {title:"Movement on any surface",description:"Camera-relative input is projected onto the current surface, which lets the spider move across floors, walls, and angled geometry while keeping the force that holds it to that surface.",details:["Surface-aligned movement vectors","Preserved normal velocity","Sphere cast prevents movement through vertical walls"]},
    {title:"Camera built for a tiny character",description:"The camera follows the spider’s orientation but checks the space between the target and camera every frame. When furniture or walls get in the way, it pulls forward instead of clipping through them.",details:["Clamped vertical rotation","Line cast collision check","Position follows the spider’s local up direction"]},
    {title:"One interaction route",description:"A central manager raycasts from the screen, looks for the IInteractable interface, and handles prompts and input. New switches and objects can be added without rewriting the player logic.",details:["Shared IInteractable interface","Context prompt","Objects own their response to interaction"]}], outcome:"The final game combines traversal and energy-saving objectives in one room-sized level. The web swing and surface movement became the main way the player reads and navigates the space.", learning:"The biggest lesson was that movement code is never finished after the first working version. Wall sticking, camera clipping, jump resets, and swing values all needed repeated playtests before the character felt predictable." },
  { slug:"makers-fair", title:"Maker’s Fair", year:"2025", engine:"Unity VR · Meta Quest 3", duration:"8 weeks", team:"5 people", hero:"/images/makers-fair/hero.jpg", images:["/images/makers-fair/hero.jpg","/images/makers-fair/01.jpg","/images/makers-fair/02.png","/images/makers-fair/03.png","/images/makers-fair/04.png"], summary:"A VR construction game about building a cart by hand: place planks, hammer nails, attach wheels, and find out whether the structure survives a stress test.", brief:"We wanted to make something about losing practical creativity when every problem is handed over to AI. Instead of explaining that idea in text, the game asks the player to build a physical object with their own hands inside VR.", role:"I implemented the construction mechanics, including plank grouping, nails, hammering, welding, wheels, and the final stress test. I also helped with task guidance, level layout, debugging, and keeping the team’s work aligned during the eight-week block.", tags:["Unity","C#","VR physics","XR Interaction Toolkit","Systems design"], links:[{label:"GitHub",href:"https://github.com/lvmbrxu/Makers-Fair"}], systems:[
    {title:"Runtime construction groups",description:"Planks join dynamic groups as the player connects them. When two existing groups meet, their members and references merge into one structure rather than creating separate chains of joints.",details:["Fast group membership lookups","Automatic group merging","Temporary kinematic following during rapid manipulation"]},
    {title:"Hammering with visible progress",description:"Only a valid hammer collision moves a nail. Each hit advances the nail and, once the placement is valid, a short sequence releases held objects, cleans up interaction components, and creates the final connection.",details:["Tool and target validation","Incremental nail depth","Sequenced physics-state changes"]},
    {title:"A stress test with two outcomes",description:"The game totals the mass of the constructed cart and its connected wheels. A valid cart is pushed forward; an overweight structure breaks its joint network and throws the pieces apart.",details:["Recursive mass check","Sustained force for success","Impulse and torque for failure"]}], outcome:"The result was a complete VR loop: collect pieces, assemble a cart, attach wheels, and test the build. The systems had to stay stable even when players moved connected objects quickly and in unexpected ways.", learning:"This project forced me to understand where Unity’s physics joints become unstable. Solver settings helped, but the better solution was often to control when objects were fully physical and when they temporarily followed a leader." },
];

export function getProject(slug:string){ return projects.find((project)=>project.slug===slug); }
